# Generated by Django 5.1.6 on 2025-02-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allapps',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
