# Generated by Django 5.1.6 on 2025-02-23 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_allapps_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allapps',
            name='slug',
        ),
    ]
